apiVersion: v1
kind: ConfigMap
metadata:
  name: aiatest-config
  namespace: namespace-workflow-1756198567872
  labels:
    app.kubernetes.io/name: aiatest
    kubernetes.azure.com/generator: devhub
data: